name: JMeter Test

# Triggers the workflow on pull requests and at midnight daily
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC daily

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # This specifies the JDK distribution
        java-version: '11'

    - name: Install dependencies
      run: npm install

    - name: Run JMeter Test
      run: npm run test:jmeter

    - name: Upload JMeter results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: results.jtl
