name: JMeter Test

on: 
    pull_request:
        branches:
            - main
    schedule:
        - cron: '0 0 * * *' # This runs the workflow at midnight UTC every day

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xvzf apache-jmeter-5.4.1.tgz
        export JMETER_HOME=$(pwd)/apache-jmeter-5.4.1
        export PATH=$JMETER_HOME/bin:$PATH

    - name: Run JMeter Test
      run: |
        jmeter -n -t test/jmeter/test-plan.jmx-l results.jtl

    - name: Upload JMeter results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: results.jtl
